---
name: "Deploys a Helm Chart"
description: |
  This action deploys a Helm chart to a registry.
author: martoc
inputs:
  registry:
    description: "Registry to deploy from. Valid values: gcp, aws"
    required: true
  region:
    description: "Region to deploy from. Valid values: Google Cloud or AWS regions"
    required: true
  repository_name:
    description: "Repository Name"
    required: true
  environment:
    description: "Environment"
    required: false
    default: ""
  gcp_project_id:
    description: "Google Cloud Project ID (required for GCP registry)"
    required: false
    default: ""
  workload_identity_provider:
    description: "Workload Identity Provider (required for GCP registry)"
    required: false
    default: ""
  service_account:
    description: "Service Account (required for GCP registry)"
    required: false
    default: ""
  cluster_name:
    description: "Kubernetes cluster name (required for GCP and AWS registries)"
    required: false
    default: ""
  aws_role_arn:
    description: "AWS IAM Role ARN for OIDC authentication (required for AWS registry)"
    required: false
    default: ""
  aws_role_arn_registry:
    description: "AWS IAM Role ARN for OIDC authentication (required for AWS registry)"
    required: false
    default: ""
  chart_name:
    description: "Chart Name"
    required: true
  chart_version:
    description: "Chart Version"
    required: true
  chart_value_file:
    description: "Chart Values File"
    required: true
  version:
    description: "Version"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v3
      with:
        version: 499.0.0
      if: ${{ inputs.registry == 'gcp' }}
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v3
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}
      if: ${{ inputs.registry == 'gcp' }}
    - name: Configure GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        location: ${{ inputs.region }}
        cluster_name: ${{ inputs.cluster_name }}
      if: ${{ inputs.registry == 'gcp' }}
    - name: Login to GCP Artifact Registry
      shell: sh
      run: |
        gcloud auth print-access-token | helm registry login -u oauth2accesstoken --password-stdin ${{ inputs.region }}-docker.pkg.dev
      if: ${{ inputs.registry == 'gcp' }}
    - name: Deploy to GCP
      shell: sh
      run: |
        if [ -z "${{ inputs.version }}" ]; then
          echo "No version provided"
        else
          export TAG_VERSION="${{ inputs.version }}"
        fi
        echo "TAG_VERSION=${TAG_VERSION}"
        echo "Chart Values:"
        cat "${{ inputs.chart_value_file }}"
        helm template \
          oci://${{ inputs.region }}-docker.pkg.dev/${{ inputs.gcp_project_id }}/${{ inputs.repository_name }}/${{ inputs.chart_name }} \
          --version ${{ inputs.chart_version }} \
          --values ${{ inputs.chart_value_file }} \
          --set appVersion="${TAG_VERSION}" \
          --set environment="${{ inputs.environment }}" \
          --set gcpProjectId="${{ inputs.gcp_project_id }}" \
          --set region="${{ inputs.region }}" > deployment.yaml
          echo "======> Generated deployment.yaml:"
          cat deployment.yaml
      if: ${{ inputs.registry == 'gcp' }}
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws_role_arn_registry }}
        aws-region: ${{ inputs.region }}
      if: ${{ inputs.registry == 'aws' }}
    - name: Login to AWS ECR
      shell: sh
      run: |
        AWS_ACCOUNT_ID=$(echo "${{ inputs.aws_role_arn_registry }}" | cut -d':' -f5)
        if [ -z "${AWS_ACCOUNT_ID}" ]; then
          echo "Error: Failed to extract AWS account ID from aws_role_arn_registry ('${{ inputs.aws_role_arn_registry }}')." >&2
          echo "Please ensure it is a valid IAM role ARN, e.g., arn:aws:iam::<account-id>:role/<role-name>." >&2
          exit 1
        fi
        aws ecr get-login-password --region ${{ inputs.region }} | \
          helm registry login --username AWS --password-stdin "${AWS_ACCOUNT_ID}.dkr.ecr.${{ inputs.region }}.amazonaws.com"
      if: ${{ inputs.registry == 'aws' }}
    - name: Deploy from AWS ECR
      shell: sh
      run: |
        AWS_ACCOUNT_ID=$(echo "${{ inputs.aws_role_arn_registry }}" | cut -d':' -f5)
        if [ -z "${{ inputs.version }}" ]; then
          echo "No version provided"
        else
          export TAG_VERSION="${{ inputs.version }}"
        fi
        echo "TAG_VERSION=${TAG_VERSION}"
        echo "Chart Values:"
        cat "${{ inputs.chart_value_file }}"
        helm template \
          oci://${AWS_ACCOUNT_ID}.dkr.ecr.${{ inputs.region }}.amazonaws.com/${{ inputs.repository_name }}/${{ inputs.chart_name }} \
          --version ${{ inputs.chart_version }} \
          --values ${{ inputs.chart_value_file }} \
          --set appVersion="${TAG_VERSION}" \
          --set environment="${{ inputs.environment }}" \
          --set region="${{ inputs.region }}" > deployment.yaml
          echo "====== BEING deployment.yaml ======"
          cat deployment.yaml
          echo "====== END deployment.yaml ======"
      if: ${{ inputs.registry == 'aws' }}
    - name: Set artifact name
      id: artifact-name
      shell: sh
      run: |
        ARTIFACT_NAME=$(echo "deployment-yaml-${{ inputs.chart_value_file }}" | tr '/' '-')
        echo "name=${ARTIFACT_NAME}" >> $GITHUB_OUTPUT
    - name: Store deployment.yaml artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.artifact-name.outputs.name }}
        path: deployment.yaml
        retention-days: 30
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws_role_arn }}
        aws-region: ${{ inputs.region }}
      if: ${{ inputs.registry == 'aws' }}
    - name: Configure EKS credentials
      shell: sh
      run: |
        aws eks update-kubeconfig \
          --name "${{ inputs.cluster_name }}" \
          --region "${{ inputs.region }}"
      if: ${{ inputs.registry == 'aws' }}
    - name: kubectl apply
      shell: sh
      run: |
        kubectl apply -f deployment.yaml
